#!/bin/bash

# Docker command helpers

alpine() {
  docker run --rm -it bentruyman/alpine "$@"
}

iex() {
  docker run --rm -it \
    -v $(pwd):/data/app \
    -v $HOME/.hex:/root/.hex \
    -v $HOME/.mix:/root/.mix \
    -w /data/app \
    bentruyman/elixir-dev iex "$@"
}

mix() {
  docker run --rm -it \
    -v $(pwd):/data/app \
    -v $HOME/.hex:/root/.hex \
    -v $HOME/.mix:/root/.mix \
    -w /data/app \
    bentruyman/elixir-dev mix "$@"
}

node() {
  docker run --rm -it \
    -v $(pwd):/data/app \
    -w /data/app \
    bentruyman/node-dev node "$@"
}

npm() {
  docker run --rm -it \
    -v $(pwd):/data/app \
    -v $HOME/.npm:/root/.npm \
    -w /data/app \
    bentruyman/node-dev npm --no-bin-links "$@"
}
